### PR TITLE
Develop/refactor  default defines

### PR DESCRIPTION
**Pull request by thecozies**
Please look through config options that I've changed, or suggest new default changes!

### CODE REVIEW

**Review by Reonu — CHANGES_REQUESTED** [review]
disable `NO_SLEEP` and we good

**Review by Reonu — APPROVED** [review]
based

**Review by Mr-Wiseguy — APPROVED** [review]

**Review by Mr-Wiseguy — APPROVED** [review]

**Review by axollyon — CHANGES_REQUESTED** [review]
some comments before we finalize
- What benefit is there to leaving `BETTER_REVERB` disabled by default? (If there's performance costs for it, they should be detailed in its comment)
- Not everyone likes using `BLUE_COIN_SWITCH_RETRY`, maybe disable by default?
- Typo: `config_movement.h` line 16, "_Percise_ turning control"
- Typo: `config_objects.h` line 39, "shoot his _partical_ in any direction"

**Comment by Reonu** [comment]
>     * What benefit is there to leaving `BETTER_REVERB` disabled by default? (If there's performance costs for it, they should be detailed in its comment)
It does have performance implications on console. Agree with the comment thing
>     * Not everyone likes using `BLUE_COIN_SWITCH_RETRY`, maybe disable by default?
idc

**Review by axollyon — APPROVED** [review]
lgtm

**Review by Mr-Wiseguy — APPROVED** [review]

**Pull request merged**
