### PR TITLE
Support pre word-swapped textures, fix puppyprint rendering for lowercase z and tilde, minor font fixes

### PR DESCRIPTION
**Pull request by LucretiaArc**
This is mostly to fix the incorrect rendering of lowercase z and tilde by puppyprint, which I think was caused by the weirdly sized font textures (672x12). I've rearranged them to 128x60, which has fixed the issue, but I've also taken the opportunity to fix a few other minor things:
- Removed the goddamn J measure, which was only needed because the font textures were wider than 512px
- Fixed argument order typos in texture loads
- FONT_OUTLINE: removed black pixel from '%'
- FONT_PLAIN: removed part of 'y' glyph encroaching on 'x'
- FONT_PLAIN: fixed alignment of '~'
- FONT_VANILLA: fixed inconsistent intensity (all pixels are now 0% or 100% intensity)

The new font texture size does fit fewer characters (84 → 80), so the symbols that were previously displayed as rectangles have been cut. The upshot of this is that the characters without reasonable glyphs are now consistent about not drawing anything. If we really do need to preserve the behaviour of those characters, a 32x252 texture will fit them and still resolve the lowercase z/tilde issue.

### CODE REVIEW

**Review by gheskett — COMMENTED** [review]
I'll look at this more thoroughly later, but ultimately I think I'm fine with this change primarily because of the funky behavior with the characters observed past 512px.

With that said, the lack of characters is probably one of the weakest parts of Puppyprint, so we'll want to figure out a means of supporting an additional set of textures for each font to handle less common characters. We still need to be careful in how we implement this because additional texture loads are not good for performance, however it'd be nice to be able to support the entirety of the vanilla font's characters (or beyond).

Puppyprint also has a few command characters being reserved that probably shouldn't remain reserved long-term (i.e. < and >). This should be changed so that they match the implementation of 3.0 ASCII. All of this may be out of scope of this PR for now though.

Personally I believe this PR should be rebased to the 3.0 branch, as people often make their own changes to the Puppyprint textures.

**Comment by LucretiaArc** [comment]
It probably makes sense to keep the original request out of 2.4 if removing the extra characters or rearranging the font texture will be a problem for compatibility.

I've added a flag to n64graphics that lets you generate pre word-swapped textures for most texture formats, which means I can include a fix for the rendering issue that's compatible with the existing font textures (they just need to be renamed). I think it's a better solution, and (hopefully) not so intrusive as to need to wait for 3.0.

The changes to the texture layout have been reverted and some other minor stuff has been fixed, so here's what this changes now:
- n64graphics: added the ability to generate pre word-swapped textures
- n64graphics: in import mode, the output file is now opened after texture data has been converted, which stops an empty file from being created if an error is encountered during conversion
- Pre word-swapped textures will now be created during the build process for textures with a filename ending in (format).preswap.png
- Puppyprint fonts now use pre word-swapped textures to fix the rendering issue
- Fixed argument order typos in puppyprint texture loads
- FONT_DEFAULT: removed part of '+' glyph encroaching on ','
- FONT_DEFAULT: removed a few weird pixels from 'Z'
- FONT_OUTLINE: removed black pixel from '%'
- FONT_PLAIN: removed part of 'y' glyph encroaching on 'x'
- FONT_PLAIN: fixed alignment of '~'
- FONT_VANILLA: fixed inconsistent intensity (all pixels are now 0% or 100% intensity)

**Review by gheskett — CHANGES_REQUESTED** [review]
We've wanted to support texture swapping for awhile but nobody has gotten to it in a long while, so this is an extremely welcome change. But now that we don't have to use preswapped binary files for this, we should probably replace the fasttext instance with an actual png. I believe it's just the exact same thing as `custom_text2` but I don't remember if it had minor font differences (not that it really matters tbh).

I would suggest keeping this texture as a separate reference for fasttext for 2 reasons:
1. Implementations don't use the same code, and Puppyprint is toggleable via define.
2. Eventually we'll want a tool that allows us to more tightly pack textures for Puppyprint, and idk if we'll be able to use a preswapped texture if we want to do that. Even if we can, fasttext doesn't support texture packing.

**Comment by LucretiaArc** [comment]
Done. The new texture is converted from the binary file fasttext was using before, which does have some font differences.

**Comment by gheskett** [comment]
Oh right, the uppercase font is different. I've always hated that because hexadecimal looks weird lol, probably for the best if we just replace it with the same Puppyprint texture.

**Comment by LucretiaArc** [comment]
Alright, I've changed the uppercase letters in the fasttext font but kept the lowercase ones as is, since puppyprint's font needs to be slightly different for some lowercase letters.

While we're fixing annoyances in the outline font, I've adjusted some of the uppercase letters in both versions of the texture where the characters looked a bit wonky.

image

**Review by gheskett — APPROVED** [review]
LGTM (though the fact that Puppyprint has to do that weird vertical shift with those lowercase characters feels dumb)

**Comment by gheskett** [comment]
I think I am going to merge this. Unfortunately this will probably make texture packing impossible, but it doesn't seem like we had much of a choice anyway (considering rendering doesn't even work properly with the old implementation).

**Pull request merged**
