### PR TITLE
Improved movement config documentation related to turning around

### LINKED ISSUE #270: Rename GROUND_TURN_FIX and GROUND_TURNING_AROUND_FIX
This is an effort to reduce opinionated `FIX` define names, especially these that fundamentally change gameplay.

___

`GROUND_TURNING_AROUND_FIX`  -> `SIDE_FLIP_AT_LOW_SPEEDS` AND `SIDE_FLIP_WHILE_TURNING_AROUND` 
    - `SIDE_FLIP_AT_LOW_SPEEDS`: just checks if velocity is >= 0 and stick held back
    - `SIDE_FLIP_WHILE_TURNING_AROUND`: points mario towards your intended direction while turning around and allows you to turn around again

___

`GROUND_TURN_FIX` -> `VELOCITY_BASED_TURN_SPEED`: Turn faster while moving slower

### PR DESCRIPTION
**Pull request by thecozies**
Fixes #270 

This splits `GROUND_TURNING_AROUND_FIX` into `SIDE_FLIP_AT_LOW_SPEEDS` and `RESET_DIRECTION_WHEN_TURNING_AROUND`, and renames `GROUND_TURN_FIX` to `VELOCITY_BASED_TURN_SPEED`, and removes dead code

### CODE REVIEW

**Comment by thecozies** [comment]
**DO NOT MERGE** until I rebase after #269 is finalized/merged

**Review by Mr-Wiseguy — APPROVED** [review]
I like these names, these are way too subjective for "fix" and "better".

**Review by axollyon — APPROVED** [review]
lgtm, good names

**Review by Reonu — APPROVED** [review]
lgtm, it is definitely a subjective thing

**Pull request merged**
