### PR TITLE
Update readme with better credits

### PR DESCRIPTION
**Pull request by Reonu**
Better credits for individual contributors

### CODE REVIEW

**Review by thecozies — APPROVED** [review]
looks good

**Review by Mr-Wiseguy — CHANGES_REQUESTED** [review]
Typo for silhouette

**Review by Mr-Wiseguy — APPROVED** [review]
Lgtm, but this would also probably be a good time to remove callouts to specific people from other areas of the code (like level_defines.h, extended_bounds.h and config.h)

**Review by thecozies — APPROVED** [review]
i approve of this even more than last time

**Comment by Reonu** [comment]
why don't you approve the presence of deez nuts in your mouth

**Comment by axollyon** [comment]
readma balls

**Review by Mr-Wiseguy — APPROVED** [review]

**Pull request merged**
