### PR TITLE
Disable AUTO_LOD by default to fix some broken vanilla models (doors).

### PR DESCRIPTION
**Pull request by Arceveti**

### CODE REVIEW

**Review by thecozies — CHANGES_REQUESTED** [review]
shouldnt the door be fixed instead? this is a pretty amazing feature on emulator that gets lost

**Comment by Arceveti** [comment]
> What's broken about doors with LOD disabled?

Since all AUTO_LOD does is make GEO_PROCESS_RANGE always read the camera distance as 50, it forces the doors to use their "near" model, which has the star labels on the transparent layer instead of the decal layer, which causes z-fighting and other issues.

> shouldnt the door be fixed instead? this is a pretty amazing feature on emulator that gets lost
Most things look fine using their "near" model from far away, but for stuff that has layer changes, it causes additional issues. In vanilla, as far as I can tell, only doors have a layer change. Custom objects might run into the same issues though.

**Comment by thecozies** [comment]
i wouldnt say this is a bug thats blocking master, this has been around since the dawn of time (this define) so lets hold off until post merge

**Comment by Reonu** [comment]
`AUTO_LOD` will remain on by default so no point in having this branch

**Pull request closed without merging**
