### PR TITLE
fixed hi score flashing

### PR DESCRIPTION
**Pull request by thecozies**

### CODE REVIEW

**Comment by thecozies** [comment]
https://user-images.githubusercontent.com/79979276/146220353-e3cb9c09-39e3-4bd3-954e-4a36188328f8.mp4

**Comment by Mr-Wiseguy** [comment]
So the issue is that the early return was preventing the dialog color timer from updating, right? What changes made this a problem here and not in vanilla? Other than being curious about that the changes look good to me.

**Comment by thecozies** [comment]
> So the issue is that the early return was preventing the dialog color timer from updating, right? What changes made this a problem here and not in vanilla? Other than being curious about that the changes look good to me.

yeah this is essentially reverted back to vanilla except s32 instead of s16 mode

**Review by Mr-Wiseguy — APPROVED** [review]

**Comment by Mr-Wiseguy** [comment]
Gotcha, sounds good.

**Comment by thecozies** [comment]
that variable just needed to keep changing so that the color could be derived from it. there's a sins function thats used on that global var that modulates env color from 0 to 255. when this value is 0 the env color was white

**Pull request merged**
