### PR TITLE
S2DEX Text Engine changes

### PR DESCRIPTION
**Pull request by someone2639**

### CODE REVIEW

**Comment by someone2639** [comment]
overview of changes:
-the engine is now transient, pulling from `someone2639/S2DEX-Text-Engine -b HackerSM64` on first build and referencing that as necessary
-area.c now has a guarded render kernel for deferred prints so the setup is now completely minimal

**Comment by Reonu** [comment]
Why are you PRing to 2.0.1

**Comment by someone2639** [comment]
too many branches [😔](https://emojipedia.org/pensive-face/) what's the right one

**Comment by Reonu** [comment]
[develop/2.1.0](https://github.com/Reonu/HackerSM64/tree/develop/2.1.0)

**Comment by someone2639** [comment]
epically updated

**Comment by someone2639** [comment]
theres still some weird files im gonna rebase on 2.1.0 and maybe it'll be more clean

**Pull request closed without merging**
