### PR TITLE
Move frame and z buffers to set positions for better performance

### PR DESCRIPTION
**Pull request by aglab2**

### CODE REVIEW

**Review by gheskett — CHANGES_REQUESTED** [review]
This is crashing at the file select screen.

image

**Comment by Reonu** [comment]
marking this as 2.1 unless anyone disagrees

**Comment by aglab2** [comment]
I'd call it vNext for now, I need to look more into it clearly. Not sure I wll be able to figure out all the pitfalls soon.

**Comment by aglab2** [comment]
Moved to https://github.com/HackerN64/HackerSM64/pull/737 with better implementation

**Pull request closed without merging**
