### PR TITLE
Added support for windows MinGW build

### PR DESCRIPTION
**Pull request by aglab2**

### CODE REVIEW

**Review by gheskett — APPROVED** [review]
Why though lol

(Well good thing I fixed that custom audio compiler issue a long time ago that at the time literally did not matter)

**Comment by aglab2** [comment]
This change allows to use MinGW without WSL. A work in progress guide is available at https://github.com/aglab2/winn64libs/blob/main/README.md

**Comment by gheskett** [comment]
Could you also work on porting that as an additional method to the [HackerSM64 Wiki](https://github.com/HackerN64/HackerSM64/wiki/Installing-HackerSM64) tutorial once it's ready?

**Comment by aglab2** [comment]
Yeah, that would be the great final goal to update wiki when 2.3.0 will be closer to release level of quality and some hackers try out MinGW.

**Pull request merged**
