### PR TITLE
derive margin_radius from radius after capping at 200

### PR DESCRIPTION
**Pull request by thecozies**
I haven't seen frame's wall patch but maybe this way incorrectly translated, or was done wrong initially.

https://user-images.githubusercontent.com/79979276/147650886-579d7acd-a466-47cc-982f-b19c3a09b8f2.mp4

### CODE REVIEW

**Comment by thecozies** [comment]
Fixes #259

**Comment by thecozies** [comment]
really, the only actors possibly affected by this change are actors that have huge collision radiuses, in vanilla that's only the racing penguin.

**Review by Reonu — APPROVED** [review]
what if we slid under the CCM cottage 😳

**Review by Mr-Wiseguy — APPROVED** [review]
Good catch

**Pull request merged**
