### PR TITLE
moved CASTLE_MUSIC_FIX into level specific checks

### LINKED ISSUE #432: CASTLE_MUSIC_FIX define should be removed and just integrated into ENABLE_VANILLA_LEVEL_SPECIFIC_CHECKS
This is the very definition of a vanilla level check. I made it a define before ENABLE_VANILLA_LEVEL_SPECIFIC_CHECKS was a thing iirc.

I'll handle this one

### PR DESCRIPTION
**Pull request by Reonu**
This define is unnecesary

Fixes #432

### CODE REVIEW

**Review by gheskett — APPROVED** [review]
Looks correct to me

**Comment by arthurtilly** [comment]
looks good

**Comment by thecozies** [comment]
needs merge conflicts resolved

**Comment by Reonu** [comment]
@thecozies

**Pull request merged**
